### ISSUE TITLE
Italian "Get it" link points to EN

### ISSUE THREAD

**Issue by hawake** [openSUSE/old-landing-page#10]
Hi,
in the italian version of the landing page, the "Get it" link is still pointing to the english wiki. So it should be it.opesuse.org instead of en.opensuse.org.

Thanks in advance!

Bye
hawake

**Comment by ggardet** [comment]
Hi,

it is "translated" like this in the PO file (opensuse-org.it.po). Please contact the Italian translation team:
https://en.opensuse.org/OpenSUSE_Localization_Teams
so that they fix it in the PO file.

Guillaume

**Comment by hawake** [comment]
Hi,
It's just a change here [ https://github.com/openSUSE/landing-page/blob/master/it/index.shtml from ], line 82, from en to it. To send a fix i have to fork the whole repository?

Thanks,

hawake

**Comment by ggardet** [comment]
Le 08/03/2013 16:18, hawake a écrit :

> Hi,
> It's just a change here [ https://github.com/openSUSE/landing-page/blob/master/it/index.shtml from ], line 82, from en to it. To send a fix i have to fork the whole repository?

No, you need to fix it in the PO file. Otherwise your change will be overwritten on the next HTML file generation from the PO file.

Guillaume

**Comment by hawake** [comment]
Ok. Understood.

Thanks again,

Bye
hawake

**Comment by ancorgs** [comment]
This has being lying around here since more than a year ago. Closing it. Not a bug in this repository anyway (as previously stated).
