### ISSUE TITLE
Missing translations of landing page: "ar", "ca" and "el".

### ISSUE THREAD

**Issue by Davidmp1** [openSUSE/old-landing-page#17]
There is no deployed version of www.opensuse.org in "ar", "ca" or "el".
And in the language selection box of http://software.opensuse.org/131/ca the "català" item appears duplicated.
David

**Comment by ancorgs** [comment]
It appears duplicated because you are viewing the page in Catalonian. The current language always appears twice (in the first place and in its usual place). It's more a general (and old) bug than an issue with "català".

I will add the missing languages in www.opensuse.org ("el" is there, though).

**Comment by Davidmp1** [comment]
This is just a reminder of the issue. Encountered any problem? Busy? Thanks a lot.

**Comment by Davidmp1** [comment]
Will www.opensuse.org be visible in "ca" and in "ar" for the release of openSUSE 13.2? Thanks.

**Comment by ancorgs** [comment]
Sure it will be. Sorry for the delay (a little bit busy with other stuff), but I promise it will be for the release. Count on it.

**Comment by ancorgs** [comment]
Already added and deployed both "ar" and "ca" (and remove "sk" which was in fact untranslated). A reload of the page to erase the browser cache will most likely be necessary to see the changes.

**Comment by Davidmp1** [comment]
Thank you very much!

It's my default page, so I have seen it immidiately as soon as I have
opened Firefox.

2014-10-17 15:18 GMT+02:00 Ancor Gonzalez Sosa notifications@github.com:
